#!/usr/bin/python
from os import listdir
from subprocess import run
from argparse import ArgumentParser
import tomllib
import logging


def pre_build():
    logging.debug("BEGIN PRE-BUILD ACTIONS")


def build(build_config, live=False, draft=False, spell=False, verbose=False):
    logging.debug("BEGIN BUILD")

    # Spell check
    if spell:
        run(["aspell", "--mode=tex", "check", build_config["build"]["TEX_NAME"]])
        if live:
            logging.warning("Live mode enabled: spell check will only run once.")

    # Start making the command for latexmk
    command = ["latexmk"]
    if live:
        command.append("-pvc")
    if verbose:
        command.append("-verbose")
    else:
        command.append("-silent")
    command += [
        "-" + build_config["build"]["LATEX"],
        "--output-directory=" + build_config["build"]["OUT_DIR"],
        "-aux-directory=" + build_config["build"]["AUX_DIR"],
        "-halt-on-error",
        "-interaction=nonstopmode",
        build_config["build"]["TEX_NAME"],
    ]

    logging.debug("Working directory: " + str(listdir()))
    logging.debug("Latexmk command: " + str(command))

    run(command)


def post_build():
    logging.debug("BEGIN POST-BUILD ACTIONS")


def parse_arguments():
    parser = ArgumentParser("./build")
    parser.add_argument(
        "-l", "--live", dest="live", action="store_true", help="specify build type"
    )
    parser.add_argument(
        "-d", "--draft", dest="draft", action="store_true", help="not include images"
    )
    parser.add_argument(
        "-s", "--spell-check", dest="spell", action="store_true", help="enable aspell"
    )
    parser.add_argument(
        "-v", "--verbose", dest="verbose", action="store_true", help="make verbose"
    )
    args = parser.parse_args()

    with open("build.toml", "rb") as f:
        build_config = tomllib.load(f)

    return args, build_config


def main():
    args, build_config = parse_arguments()
    live, draft, spell, verbose = args.live, args.draft, args.spell, args.verbose

    if verbose:
        logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.DEBUG)
    else:
        logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.WARNING)

    logging.debug("TEX_NAME: " + build_config["build"]["TEX_NAME"])
    logging.debug("AUX_DIR: " + build_config["build"]["AUX_DIR"])
    logging.debug("OUT_DIR: " + build_config["build"]["OUT_DIR"])
    logging.debug("OUT_NAME: " + build_config["build"]["OUT_NAME"])
    logging.debug("LATEX: " + build_config["build"]["LATEX"])
    logging.debug("Arguments: " + str(args))

    pre_build()
    build(build_config, live, draft, spell, verbose)
    post_build()


if __name__ == "__main__":
    main()
