#!/usr/bin/python
from subprocess import run
import argparse
import logging
from os import listdir

TEX_NAME = "main.tex"
AUX_DIR = "./tmp"
OUT_DIR = "./"
OUT_NAME = "main"

LATEX = "pdflatex"


def build(live=False, draft=False, verbose=False):
    command = ["latexmk"]
    if live:
        command.append("-pvc")

    if verbose:
        command.append("-verbose")
    else:
        command.append("-silent")

    command += [
        "-" + LATEX,
        "--output-directory=" + OUT_DIR,
        "-aux-directory=" + AUX_DIR,
        "-halt-on-error",
        "-interaction=nonstopmode",
        TEX_NAME,
    ]

    logging.debug("Working directory: " + str(listdir()))
    logging.debug("Latexmk command: " + str(command))

    run(command)


def main():
    parser = argparse.ArgumentParser("build.py")
    parser.add_argument(
        "-l", "--live", dest="live", action="store_true", help="specify build type"
    )
    parser.add_argument(
        "-d", "--draft", dest="draft", action="store_true", help="not include images"
    )
    parser.add_argument(
        "-s", "--spell-check", dest="spell", action="store_true", help="enable aspell"
    )
    parser.add_argument(
        "-v", "--verbose", dest="verbose", action="store_true", help="make verbose"
    )
    args = parser.parse_args()
    live, draft, spell, verbose = args.live, args.draft, args.spell, args.verbose

    if verbose:
        logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.DEBUG)
    else:
        logging.basicConfig(format="%(levelname)s: %(message)s", level=logging.WARNING)

    logging.debug("Arguments: " + str(args))

    if spell:
        run(["aspell", "--mode=tex", "check", TEX_NAME])

    build(live, draft, verbose)


if __name__ == "__main__":
    main()
